### ISSUE TITLE
Migration from OSS 0.84.0 to AES 1.4.0 fails at step 5 "Upgrade and Restart"

### ISSUE THREAD

**Issue by awilliams219** [emissary-ingress/emissary#2609]
I originally posted this in slack.  @ark3 asked me to create an issue with the error I was receiving.

We're currently on Ambassador API Gateway 0.84.0.  We use a custom auth service.  

Upon attempting to upgrade to AES 1.4 using the directions at https://www.getambassador.io/docs/latest/topics/install/upgrade-to-edge-stack/, our upgrade fails at step 5 "Upgrade and Restart".  Before that, everything seems to work and tests just fine.  However, at that step, after restarting the aes deployment, the new aes pod never starts up.  It will just restart over and over again.

Reviewing the logs on this, I find this section that appears to be relevant:

```
2020/04/17 15:15:12 notify: update to http://localhost:8877/_internal/v0/watt?url=http%3A%2F%2Flocalhost%3A8002%2Fsnapshots%2F1 failed:
time="2020-04-17 15:15:12" level=info msg="license_secret_watch: inspecting new snapshot: looking for default/ambassador-edge-stack within 2 secrets" MAIN=license_secret_watch
time="2020-04-17 15:15:12" level=info msg="license_secret_watch: ignoring secret default/fallback-self-signed-cert" MAIN=license_secret_watch
time="2020-04-17 15:15:12" level=info msg="license_secret_watch: AES secret found (default/ambassador-edge-stack): getting license data" MAIN=license_secret_watch
time="2020-04-17 15:15:12" level=warning msg="license_secret_watch: empty decoded license data" MAIN=license_secret_watch
2020/04/17 15:15:12 notify: status 500: configuration failed
2020/04/17 15:15:12 notify: exit status 1
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: reading edge-stack-mappings.yaml (/ambassador/init-config/edge-stack-mappings.yaml)
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: YAML: using C parser
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: YAML: using C dumper
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: Parsed pod labels: {'pod-template-hash': '858cf885ff', 'product': 'aes'}
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: auth-service.default.1: NOTICE: apiVersion ambassador/v1y is not supported
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: Intercept agent not active, skipping initialization
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: HostFactory: FTC False, host_count 0
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: Creating fallback context
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: IRTLSContext setup good: <IRTLSContext fallback-self-signed-context.default rcf 8080 (fallback): hosts ['*'] secret fallback-self-signed-cert>
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: IR: watching Edge Stack
2020/04/17 15:15:12 aggregator: watch hook stderr: 2020-04-17 15:15:12 watch-hook INFO: Intercept agent not active, skipping finalization
2020/04/17 15:15:12 aggregator: watch hook stderr: 
2020/04/17 15:15:12 aggregator: found 3 kubernetes watches
2020/04/17 15:15:12 aggregator: found 0 consul watches
2020/04/17 15:15:12 kubewatchman: processing 3 kubernetes watch specs
2020/04/17 15:15:12 consulwatchman: processing 0 consul watches
2020/04/17 15:15:12 notify: python /ambassador/post_update.py --watt  http://localhost:8002/snapshots/2
2020-04-17 15:15:12 diagd 1.4.1 [P149TThreadPoolExecutor-0_6] INFO: Update requested: watt, http://localhost:8002/snapshots/2
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: copying configuration: watt, http://localhost:8002/snapshots/2 to /ambassador/snapshots/snapshot-tmp.yaml
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: reading edge-stack-mappings.yaml (/ambassador/init-config/edge-stack-mappings.yaml)
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: Parsed pod labels: {'pod-template-hash': '858cf885ff', 'product': 'aes'}
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: auth-service.default.1: NOTICE: apiVersion ambassador/v1y is not supported
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: Intercept agent not active, skipping initialization
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: HostFactory: FTC False, host_count 0
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: Creating fallback context
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: IRTLSContext setup good: <IRTLSContext fallback-self-signed-context.default rcf 8080 (fallback): hosts ['*'] secret fallback-self-signed-cert>
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: IR: starting Edge Stack
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: Intercept agent not active, skipping finalization
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: adding mappings for Edge Policy Console
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] INFO: IR: cluster cluster_127_0_0_1_8500_default is the sidecar
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] ERROR: cluster_extauth_127_0_0_1_8500_default: <RichStatus BAD error=cannot merge cluster cluster_extauth_auth_service_default: mismatched attributes grpc hostname=aes-858cf885ff-dkzf9 version=1.4.1>
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] ERROR: ambassador-edge-stack-auth.default.1: <RichStatus BAD error=auth canary cluster_extauth_auth_service_default can only change service! hostname=aes-858cf885ff-dkzf9 version=1.4.1>
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] ERROR: could not reconfigure: 
2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] ERROR: 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 874, in run
    self.load_config_watt(rqueue, url)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 1052, in load_config_watt
    self._load_ir(rqueue, aconf, fetcher, scc, snapshot)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 1066, in _load_ir
    econf = EnvoyConfig.generate(ir, "V2")
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador/envoy/common.py", line 83, in generate
    return V2Config(ir)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador/envoy/v2/v2config.py", line 53, in __init__
    V2Listener.generate(self)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador/envoy/v2/v2listener.py", line 975, in generate
    listener = listeners_by_port.get(irlistener.service_port, irlistener.use_proxy_proto)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador/envoy/v2/v2listener.py", line 652, in get
    v2listener = self[port]
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador/envoy/v2/v2listener.py", line 638, in __getitem__
    listener = V2Listener(self.config, port)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador/envoy/v2/v2listener.py", line 683, in __init__
    v2f: dict = v2filter(f, self.config)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/multi/__init__.py", line 81, in multifun
    return action(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador/envoy/v2/v2listener.py", line 290, in v2filter_authv1
    assert auth.cluster
AssertionError
2020/04/17 15:15:12 notify: update to http://localhost:8877/_internal/v0/watt?url=http%3A%2F%2Flocalhost%3A8002%2Fsnapshots%2F2 failed:
time="2020-04-17 15:15:12" level=info msg="license_secret_watch: inspecting new snapshot: looking for default/ambassador-edge-stack within 2 secrets" MAIN=license_secret_watch
time="2020-04-17 15:15:12" level=info msg="license_secret_watch: ignoring secret default/fallback-self-signed-cert" MAIN=license_secret_watch
time="2020-04-17 15:15:12" level=info msg="license_secret_watch: AES secret found (default/ambassador-edge-stack): getting license data" MAIN=license_secret_watch
time="2020-04-17 15:15:12" level=warning msg="license_secret_watch: empty decoded license data" MAIN=license_secret_watch
2020/04/17 15:15:12 notify: status 500: configuration failed
2020/04/17 15:15:12 notify: exit status 1
```
The holdup appears to be related to our auth-system:

>2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] ERROR: cluster_extauth_127_0_0_1_8500_default: <RichStatus BAD error=cannot merge cluster cluster_extauth_auth_service_default: mismatched attributes grpc hostname=aes-858cf885ff-dkzf9 version=1.4.1>
>2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] ERROR: ambassador-edge-stack-auth.default.1: <RichStatus BAD error=auth canary cluster_extauth_auth_service_default can only change service! hostname=aes-858cf885ff-dkzf9 version=1.4.1>
>2020-04-17 15:15:12 diagd 1.4.1 [P149TAEW] ERROR: could not reconfigure: 

Our auth system's yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1y
      kind: Mapping
      name: auth_login_routes-ui_mapping
      prefix: /api/core/
      rewrite: /core/
      service: auth-service:80
      bypass_auth: true
      cors:
        methods: GET, POST, OPTIONS


spec:
 ( ... typical stuff here )
```

And here's the annotation on our application that maps to the auth system:

```
apiVersion: v1
kind: Service
metadata:
  name: mcp-app-backend
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: mcp-backend_mapping
      prefix: /api/mcp
      rewrite: "/mcp"
      service: mcp-app-backend:8080
      timeout_ms: 10000
      idle_timeout_ms: 1000000
      connect_timeout_ms: 10000
      ---
      apiVersion: ambassador/v1
      kind:  AuthService
      name:  authentication
      auth_service: "auth-service"
      allowed_request_headers:
      - "x-context"
      allowed_authorization_headers:
      - "x-new-api-token"
      - "x-new-api-token-expire"
      - "x-new-api-token-valid"
      - "x-auth-token"
      - "x-auth-token-pubkey"
spec:
    ( ... again, typical stuff here)
```

**Comment by cindymullins-dw** [comment]
Closing as now out of date.  Migration paths for newer versions are [noted here](https://www.getambassador.io/docs/emissary/latest/topics/install/migration-matrix).
