### ISSUE TITLE
"Proxy: OFF (attempting to connect)" when doing edgectl connect

### ISSUE THREAD

**Issue by ocarabia-aura** [emissary-ingress/emissary#2808]
**Describe the bug**
I am not getting "full" connectivity to the cluster when using "edgectl connect" and therefore i'm not able to contact the services directly, as shown on this section: https://www.getambassador.io/docs/latest/topics/using/edgectl/edge-control/#usage-outbound-services

**To Reproduce**

1. Start the edgectl daemon
2. connect to the cluster
3. curl a service

```
 ~  sudo edgectl daemon --dns 192.168.1.1
Launching Edge Control Daemon v1.4.1 (api v1)
 ~  edgectl connect -n durian
Connecting to traffic manager in namespace ambassador...
Connected to context aura-playgrounds-eks (https://xxx.gr7.us-west-2.eks.amazonaws.com)
 ~  edgectl status
Connected
  Context:       aura-playgrounds-eks (https://xxx.gr7.us-west-2.eks.amazonaws.com)
  Proxy:         OFF (attempting to connect...)
  Interceptable: 2 deployments
  Intercepts:    0 total, 0 local
 ~  kubectl -n durian get svc | grep protected
insikt-reports-protected-svc               ClusterIP   172.20.93.228    <none>        8080/TCP
 ~  curl -L insikt-reports-protected-svc.durian:8080/health
curl: (6) Could not resolve host: insikt-reports-protected-svc.durian
```

**Expected behavior**
I would expect to get that complete connectivity to the cluster, as shown in the guide example:
```
$ edgectl status
Connected
  Context:       default (https://localhost:6443)
  Proxy:         ON (networking to the cluster is enabled)
  Intercepts:    Unavailable: no traffic manager
```
And also to be able to curl the services, as shown in the guide too:
```
$ curl -L hello
Hello, world!
```
**Versions (please complete the following information):**
 - Ambassador:  Image: quay.io/datawire/aes:1.4.1
 - Kubernetes environment AWS
 - Version [e.g. 1.8.1]
 - edgectl (both client and daemon): 1.4.1 (Also tried with 1.5.3)

**Additional context**
An extract of the edgectl.log file, might be related:

```
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  -> apiVersion: v1
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  -> kind: Pod
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  -> metadata:
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  ->   name: teleproxy
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  ->   labels:
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  ->     name: teleproxy
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  -> spec:
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  ->   hostname: traffic-proxy
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  ->   containers:
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  ->   - name: proxy
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  ->     image: docker.io/datawire/telepresence-k8s:0.75
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  ->     ports:
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  ->     - protocol: TCP
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  ->       containerPort: 8022
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP:  -> \no newline
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 K8S: kubernetes namespace=durian
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 BRG: Setting DNS search path: durian.svc.cluster.local.
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 BRG: error setting up search path: Post http://teleproxy/api/search: dial tcp: lookup teleproxy: no such host
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 K8S: ERROR: WORKER PANICKED: Post http://teleproxy/api/search: dial tcp: lookup teleproxy: no such host
2020/06/17 17:04:50 bridge/out:  <- goroutine 98 [running]:
2020/06/17 17:04:50 bridge/out:  <- runtime/debug.Stack(0xc0005d9cc8, 0x5596a40, 0xc0003efec0)
2020/06/17 17:04:50 bridge/out:  <-     runtime/debug/stack.go:24 +0x9d
2020/06/17 17:04:50 bridge/out:  <- github.com/datawire/ambassador/pkg/supervisor.(*Supervisor).launch.func1.1.1(0xc0005d9f98)
2020/06/17 17:04:50 bridge/out:  <-     github.com/datawire/ambassador@/pkg/supervisor/supervisor.go:194 +0x57
2020/06/17 17:04:50 bridge/out:  <- panic(0x5596a40, 0xc0003efec0)
2020/06/17 17:04:50 bridge/out:  <-     runtime/panic.go:679 +0x1b2
2020/06/17 17:04:50 bridge/out:  <- github.com/datawire/ambassador/pkg/teleproxy.bridges.func1(0xc0000fb720, 0x0, 0x0)
2020/06/17 17:04:50 bridge/out:  <-     github.com/datawire/ambassador@/pkg/teleproxy/teleproxy.go:676 +0x698
2020/06/17 17:04:50 bridge/out:  <- github.com/datawire/ambassador/pkg/supervisor.(*Supervisor).launch.func1.1(0xc0005d9f98, 0xc000346f80, 0xc0000fb720)
2020/06/17 17:04:50 bridge/out:  <-     github.com/datawire/ambassador@/pkg/supervisor/supervisor.go:199 +0x7a
2020/06/17 17:04:50 bridge/out:  <- github.com/datawire/ambassador/pkg/supervisor.(*Supervisor).launch.func1(0xc000346f80, 0xc0000fb720, 0xc000710d90)
2020/06/17 17:04:50 bridge/out:  <-     github.com/datawire/ambassador@/pkg/supervisor/supervisor.go:200 +0x5f
2020/06/17 17:04:50 bridge/out:  <- created by github.com/datawire/ambassador/pkg/supervisor.(*Supervisor).launch
2020/06/17 17:04:50 bridge/out:  <-     github.com/datawire/ambassador@/pkg/supervisor/supervisor.go:189 +0xb2
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 SIG: signaling shutdown
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP: signaling shutdown
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 DKR: signaling shutdown
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 SIG: exited
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 DKR: exited
2020/06/17 17:04:50 bridge/out:  <- 2020/06/17 17:04:50 KAP: exited
2020/06/17 17:04:50 bridge/out:  <- Error: Teleproxy exited with 1 error(s):
2020/06/17 17:04:50 bridge/out:  <-   K8S: WORKER PANICKED: Post http://teleproxy/api/search: dial tcp: lookup teleproxy: no such host
2020/06/17 17:04:50 bridge/out:  <- goroutine 98 [running]:
2020/06/17 17:04:50 bridge/out:  <- runtime/debug.Stack(0xc0005d9cc8, 0x5596a40, 0xc0003efec0)
2020/06/17 17:04:50 bridge/out:  <-     runtime/debug/stack.go:24 +0x9d
```

**Comment by kflynn** [comment]
@ark3, can you offer wisdom here? Also, @ocarabia-aura, you might find our [Slack](https://d6e.co/slack) to be a good place to talk about this. 🙂

**Comment by ocarabia-aura** [comment]
> @ark3, can you offer wisdom here? Also, @ocarabia-aura, you might find our [Slack](https://d6e.co/slack) to be a good place to talk about this. 🙂

Thanks @kflynn i actually opened this issue as per recommendation of one of the guys in Slack 😅 I opened a thread there

**Comment by cindymullins-dw** [comment]
The edgectl CLI tool has been deprecated; please use the emissary-ingress helm chart instead and upgrade to 2.x or 3.x.
