### ISSUE TITLE
Segmentation violation with two oauth2 filters with same name in different namespaces

### ISSUE THREAD

**Issue by yanickbelanger** [emissary-ingress/emissary#2836]
**Describe the bug**
I have a clean AES setup, installed with Helm. When configuring two oauth2 filters, with the same name, in two different namespace, my ambassador pods go into a crash loop. The logs contain:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2095fa4]
goroutine 126 [running]:
github.com/datawire/apro/apis/getambassador.io/v1beta2.(*Origin).Validate(0xc0029e2000, 0x2bb58a0, 0x11)
	github.com/datawire/apro@/apis/getambassador.io/v1beta2/filter_oauth2.go:117 +0x184
github.com/datawire/apro/apis/getambassador.io/v1beta2.(*FilterOAuth2).Validate(0xc00065f1e0, 0xc002ab5026, 0x7, 0x2e96cc0, 0xc0004f6350, 0x2, 0x15)
	github.com/datawire/apro@/apis/getambassador.io/v1beta2/filter_oauth2.go:180 +0x17de
github.com/datawire/apro/apis/getambassador.io/v1beta2.(*FilterSpec).Validate(0xc00449ee80, 0xc00276b020, 0x13, 0xc002ab5026, 0x7, 0x2e96cc0, 0xc0004f6350, 0x1, 0x0, 0x0, ...)
	github.com/datawire/apro@/apis/getambassador.io/v1beta2/filter.go:106 +0x672
github.com/datawire/apro/apis/getambassador.io/v1beta2.(*Filter).Validate(0xc0008d91f0, 0x2e96cc0, 0xc0004f6350, 0x289e601, 0x7, 0xc000056056)
	github.com/datawire/apro@/apis/getambassador.io/v1beta2/filter.go:44 +0x91
github.com/datawire/apro/cmd/amb-sidecar/filters/controller.(*Controller).Watch.func1(0xc0029c9180)
	github.com/datawire/apro@/cmd/amb-sidecar/filters/controller/controller.go:143 +0x44b
github.com/datawire/ambassador/pkg/k8s.(*Watcher).WatchQuery.func1()
[...]
```

**To Reproduce**
1. Have a clean AES install
2. Configure two oauth2 filters, with the same name but in two different namespaces
3. Restart the ambassador pods (scale down-up deployment or delete all pods)

**Expected behavior**
The pods should start with no error.

**Versions (please complete the following information):**
 - Ambassador: 1.5.4 (docker image: docker.io/datawire/aes:1.5.4)
 - Kubernetes environment: EKS
 - Version: v1.15.11-eks-af3caf

**Comment by cindymullins-dw** [comment]
HI @yanickbelanger, could you confirm if this n?ow works with 2.x or 3.x or if the issue persists in this use case?
