### ISSUE TITLE
Ambassador pod fails to start after misconfigured mapping annotations found

### ISSUE THREAD

**Issue by masterxavierfox** [emissary-ingress/emissary#3187]
**Describe the bug**
Ambassador is reporting misconfigured service mappings in the cluster and throwing the following log on reboot:

```
2021-02-01 14:16:28 diagd 1.11.0 [P18TAEW] INFO: starting Scout checker and timer logger
2021-02-01 14:16:28 diagd 1.11.0 [P18TAEW] INFO: starting event watcher
2021/02/01 14:16:29 error parsing annotations: error converting YAML to JSON: yaml: line 21: did not find expected key
2021/02/01 14:16:29 Bootstrapped! Computing initial configuration...
2021-02-01 14:16:29 diagd 1.11.0 [P18TAEW] ERROR: could not reconfigure: while parsing a block mapping
  in "<unicode string>", line 2, column 1
did not find expected key
  in "<unicode string>", line 22, column 4
2021-02-01 14:16:29 diagd 1.11.0 [P18TAEW] ERROR: while parsing a block mapping
  in "<unicode string>", line 2, column 1
did not find expected key
  in "<unicode string>", line 22, column 4
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador_diag/diagd.py", line 1304, in run
    self.load_config_watt(rqueue, url)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador_diag/diagd.py", line 1453, in load_config_watt
    fetcher.parse_watt(serialization)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/fetcher.py", line 275, in parse_watt
    self.handle_k8s(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/fetcher.py", line 336, in handle_k8s
    if self.k8s_processor.try_process(obj):
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 47, in try_process
    self._process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 126, in _process
    self.delegate.try_process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 47, in try_process
    self._process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 98, in _process
    proc.try_process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 47, in try_process
    self._process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/service.py", line 211, in _process
    self.delegate.try_process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 47, in try_process
    self._process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 98, in _process
    proc.try_process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 47, in try_process
    self._process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/service.py", line 95, in _process
    self.manager.emit_annotated(NormalizedResource.from_kubernetes_object_annotation(obj))
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/resource.py", line 96, in from_kubernetes_object_annotation
    return [clean_normalize(r) for r in parse_yaml(config) if r]
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/utils.py", line 77, in parse_yaml
    return list(yaml.load_all(serialization, Loader=yaml_loader))
  File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 130, in load_all
    yield loader.get_data()
  File "/usr/lib/python3.8/site-packages/yaml/constructor.py", line 45, in get_data
    return self.construct_document(self.get_node())
  File "ext/_yaml.pyx", line 699, in _yaml.CParser.get_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 2, column 1
did not find expected key
  in "<unicode string>", line 22, column 4
2021/02/01 14:16:29 error notifying diagd: 500 INTERNAL SERVER ERROR, configuration failed
```

**To Reproduce**
1. Deploy ambassador to a cluster with no service mappings.
2. Deploy a pod with a misconfigured ambassador service mapping. In my case, there are 117 active mappings with 8 misconfigured mappings.
3. Open the ambassador diagnostics UI to check affected mappings.
4. Delete affected service mappings
5. Restart ambassador service.
6. Ambassador fails to boot the diagnostics UI does not update and you're stuck with ambassador in its last working state. 

**Expected behavior**
Usually, when you delete the mappings ambassador should start without throwing the error above. But in my case, the running ambassador service is not accepting nor reporting that I have deleted the affected mappings it's stuck reporting that i still have 8 mappings with errors and 117 active mappings in the cluster.

The 117 active mappings are service traffic without any issues but the 8 mappings are still persistent even after i delete them from the mappings CRD's.

So when I try to deploy a new pod of ambassador the service cannot boot up and fails health checks throwing the above error.

**Versions (please complete the following information):**
 - Ambassador: 1.9.0 (opensource api gateway)
 - Kubernetes environment: Aws EKS
 - Version 1.15

**Additional context**
what I have tried so far was deploying anew pod of ambassador API gateway v 1.11.0 and I still get the same error. 
Also, ambassador reports: `Configuration from 2021-01-06 07:52:21.163517 — 26 days, 8 hours, 28 minutes, 13

Also tried deploying ambassador edge stack into the same cluster this is the error i get:

```
2021/02/01 16:29:55 Warning, unable to watch ingressclasses.networking.k8s.io, unknown kind.
time="2021-02-01T16:29:57Z" level=warning msg="statsd is not in use"
time="2021-02-01 16:29:57" level=error msg="Failed to create watch on /tmp/ambassador/.config/ambassador/: Changes might require a restart: no such file or directory" func=github.com/datawire/apro/cmd/amb-sidecar.triggerOnChange file="github.com/datawire/apro/cmd/amb-sidecar/files.go:56" CMD=amb-sidecar PID=13 THREAD=/license_refresh
time="2021-02-01 16:29:58" level=error msg="0 filters configured" func="github.com/datawire/apro/cmd/amb-sidecar/filters/controller.(*Controller).Watch.func1" file="github.com/datawire/apro/cmd/amb-sidecar/filters/controller/controller.go:150" CMD=amb-sidecar PID=13 THREAD=/auth_controller
2021/02/01 16:29:58 http: proxy error: dial tcp 127.0.0.1:8004: connect: connection refused
time="2021-02-01 16:29:58" level=error msg="Bad HTTP request: status_code=502" func=github.com/datawire/apro/cmd/amb-sidecar/devportal/server.HTTPGet.func1.1 file="github.com/datawire/apro/cmd/amb-sidecar/devportal/server/http.go:72" CMD=amb-sidecar PID=13 component=devportal mhost= url="http://127.0.0.1:8877/ambassador/v0/diag/?json=true"
time="2021-02-01 16:29:58" level=error msg="HTTP error 502 from http://127.0.0.1:8877/ambassador/v0/diag/?json=true" func=github.com/datawire/apro/cmd/amb-sidecar/devportal/server.HTTPGet.func1 file="github.com/datawire/apro/cmd/amb-sidecar/devportal/server/http.go:79" CMD=amb-sidecar PID=13 component=devportal mhost= url="http://127.0.0.1:8877/ambassador/v0/diag/?json=true"
2021-02-01 16:29:58 diagd 1.11.0 [P12TMainThread] INFO: AMBASSADOR_FAST_RECONFIGURE disabled, not initializing cache
2021-02-01 16:29:58 diagd 1.11.0 [P12TMainThread] INFO: WILL NOT update Mapping status
2021-02-01 16:29:58 diagd 1.11.0 [P12TMainThread] INFO: thread count 5, listening on 0.0.0.0:8004
2021-02-01 16:29:58 diagd 1.11.0 [P12TMainThread] INFO: Ambassador 1.11.0 booted
[2021-02-01 16:29:58 +0000] [12] [INFO] Starting gunicorn 20.0.4
[2021-02-01 16:29:58 +0000] [12] [INFO] Listening at: http://0.0.0.0:8004 (12)
[2021-02-01 16:29:58 +0000] [12] [INFO] Using worker: threads
[2021-02-01 16:29:58 +0000] [33] [INFO] Booting worker with pid: 33
2021-02-01 16:29:58 diagd 1.11.0 [P33TAEW] INFO: starting Scout checker and timer logger
2021-02-01 16:29:58 diagd 1.11.0 [P33TAEW] INFO: starting event watcher
2021/02/01 16:29:59 error parsing annotations: error converting YAML to JSON: yaml: line 21: did not find expected key
2021/02/01 16:29:59 Taking K8sSecret snapshot.SecretRef{Namespace:"default", Name:"ambassador-edge-stack"}
2021/02/01 16:29:59 Taking K8sSecret snapshot.SecretRef{Namespace:"default", Name:"fallback-self-signed-cert"}
2021/02/01 16:29:59 Bootstrapped! Computing initial configuration...
2021-02-01 16:29:59 diagd 1.11.0 [P33TAEW] ERROR: could not reconfigure: while parsing a block mapping
  in "<unicode string>", line 2, column 1
did not find expected key
  in "<unicode string>", line 22, column 4
2021-02-01 16:29:59 diagd 1.11.0 [P33TAEW] ERROR: while parsing a block mapping
  in "<unicode string>", line 2, column 1
did not find expected key
  in "<unicode string>", line 22, column 4
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador_diag/diagd.py", line 1304, in run
    self.load_config_watt(rqueue, url)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador_diag/diagd.py", line 1453, in load_config_watt
    fetcher.parse_watt(serialization)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/fetcher.py", line 275, in parse_watt
    self.handle_k8s(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/fetcher.py", line 336, in handle_k8s
    if self.k8s_processor.try_process(obj):
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 47, in try_process
    self._process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 126, in _process
    self.delegate.try_process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 47, in try_process
    self._process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 98, in _process
    proc.try_process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 47, in try_process
    self._process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/service.py", line 211, in _process
    self.delegate.try_process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 47, in try_process
    self._process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 98, in _process
    proc.try_process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/k8sprocessor.py", line 47, in try_process
    self._process(obj)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/service.py", line 95, in _process
    self.manager.emit_annotated(NormalizedResource.from_kubernetes_object_annotation(obj))
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/fetch/resource.py", line 96, in from_kubernetes_object_annotation
    return [clean_normalize(r) for r in parse_yaml(config) if r]
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/utils.py", line 77, in parse_yaml
    return list(yaml.load_all(serialization, Loader=yaml_loader))
  File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 130, in load_all
    yield loader.get_data()
  File "/usr/lib/python3.8/site-packages/yaml/constructor.py", line 45, in get_data
    return self.construct_document(self.get_node())
  File "ext/_yaml.pyx", line 699, in _yaml.CParser.get_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 2, column 1
did not find expected key
  in "<unicode string>", line 22, column 4
2021/02/01 16:29:59 error notifying diagd: 500 INTERNAL SERVER ERROR, configuration failed
time="2021-02-01 16:29:59" level=warning msg="license_secret_watch: empty decoded license data" func=github.com/datawire/apro/cmd/amb-sidecar.runE.func3 file="github.com/datawire/apro/cmd/amb-sidecar/main.go:259" CMD=amb-sidecar PID=13 THREAD=/license_secret_watch
2021/02/01 16:30:04 Memory Usage 0.26Gi (66%)
    PID 1, 0.16Gi: busyambassador entrypoint
    PID 12, 0.04Gi: /usr/bin/python /usr/bin/diagd /ambassador/snapshots /ambassador/bootstrap-ads.json /ambassador/envoy/envoy.json --notices /ambassador/notices.json --port 8004 --kick kill -HUP 1
    PID 13, 0.12Gi: /ambassador/sidecars/amb-sidecar
    PID 33, 0.04Gi: /usr/bin/python /usr/bin/diagd /ambassador/snapshots /ambassador/bootstrap-ads.json /ambassador/envoy/envoy.json --notices /ambassador/notices.json --port 8004 --kick kill -HUP 1
Calling Metriton
```

**Comment by chaitushiva** [comment]
This has to be addressed

**Comment by wise0wl** [comment]
Is there any way to determine which mapping is misconfigured or how to fix?

**Comment by cindymullins-dw** [comment]
CRDs are generally recommended over annotations but even more recent 1.x (1.13, 1.14) versions should be much improved with regards to this issue.  We're currently working on an [automated config analysis utility](https://app.getambassador.io/cloud/config-analysis) that will help identify misconfigured mappings.

**Comment by rjluzardo** [comment]
> CRDs are generally recommended over annotations but even more recent 1.x (1.13, 1.14) versions should be much improved with regards to this issue. We're currently working on an [automated config analysis utility](https://app.getambassador.io/cloud/config-analysis) that will help identify misconfigured mappings.

I am currently running into this issue after trying to upgrade from 1.5.0 to 1.14.4 Is there a way to identify those mappings? I have hundred of them.
