### ISSUE TITLE
SSL certificate verification failure when running in cluster with private Certificate Authority

### ISSUE THREAD

**Issue by onkarbhat** [emissary-ingress/emissary#3284]
**Describe the bug**

In a K8s cluster that is running with a private CA certificate, Ambassador is hitting errors while connecting to the API server. 

`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.43.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/kasten (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1123)')))` 

I created a ConfigMap that contains the private CA certificate and mounted it at `/etc/ssl/certs/custom-ca-bundle.pem` with the hope that maybe Ambassador would load the new certificate if it was present in a standard path such as `/etc/ssl/certs` . But that did not help.

```
Traceback (most recent call last):

  File "/ambassador/kubewatch.py", line 376, in <module>

    main()

  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__

    return self.main(*args, **kwargs)

  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main

    rv = self.invoke(ctx)

  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/ambassador/kubewatch.py", line 236, in main

    ret = v1.read_namespace(wanted)

  File "/usr/lib/python3.8/site-packages/kubernetes/client/apis/core_v1_api.py", line 17572, in read_namespace

    (data) = self.read_namespace_with_http_info(name, **kwargs)

  File "/usr/lib/python3.8/site-packages/kubernetes/client/apis/core_v1_api.py", line 17644, in read_namespace_with_http_info

    return self.api_client.call_api('/api/v1/namespaces/{name}', 'GET',

  File "/usr/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 317, in call_api

    return self.__call_api(resource_path, method,

  File "/usr/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 150, in __call_api

    response_data = self.request(method, url,

  File "/usr/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 338, in request

    return self.rest_client.GET(url,

  File "/usr/lib/python3.8/site-packages/kubernetes/client/rest.py", line 227, in GET

    return self.request("GET", url,

  File "/usr/lib/python3.8/site-packages/kubernetes/client/rest.py", line 201, in request

    r = self.pool_manager.request(method, url,

  File "/usr/lib/python3.8/site-packages/urllib3/request.py", line 66, in request

    return self.request_encode_url(method, url, fields=fields,

  File "/usr/lib/python3.8/site-packages/urllib3/request.py", line 89, in request_encode_url

    return self.urlopen(method, url, **extra_kw)

  File "/usr/lib/python3.8/site-packages/urllib3/poolmanager.py", line 324, in urlopen

    response = conn.urlopen(method, u.request_uri, **kw)

  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen

    return self.urlopen(method, url, body, headers, retries,

  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen

    return self.urlopen(method, url, body, headers, retries,

  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen

    return self.urlopen(method, url, body, headers, retries,

  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen

    retries = retries.increment(method, url, error=e, _pool=self,

  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.43.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/kasten (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1123)')))
``` 

**To Reproduce**
1. Deploy a Kubernetes cluster with a private CA (Certificate Authority) certificate.
2. Start Ambassador. 
3. The logs will show SSL verification errors when Ambassador connects to the Kubernetes API server.

**Expected behavior**

Ambassador should load the certificates at `/etc/ssl/certs` so that SSL verification succeeds while connecting to the K8s API server. 

**Versions (please complete the following information):**
 - Ambassador: 1.9.1
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - Version [e.g. 1.8.1]

**Additional context**

 I did try the `AMBASSADOR_SSL_VERIFY_FALSE` environment variable described here - https://github.com/datawire/ambassador/pull/808 . This works, but it is an insecure option.

**Comment by cindymullins-dw** [comment]
Emissary doesn't detect changes when the cert is stored in a file path, so it is recommended to use a Kubernetes secret instead.
