### ISSUE TITLE
aes:1.12.1 is crashing with error 500 on mappings with prefix set to ""

### ISSUE THREAD

**Issue by Nilsty** [emissary-ingress/emissary#3286]
**Describe the bug**
On start of the aes:1.12.1 image the container logs show:
```
2021-03-23 13:34:54 diagd 1.12.1 [P34TAEW] ERROR: could not reconfigure: prefix
2021-03-23 13:34:54 diagd 1.12.1 [P34TAEW] ERROR: prefix
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/resource.py", line 87, in __getattr__
    return self[key]
KeyError: 'prefix'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador_diag/diagd.py", line 1304, in run
    self.load_config_watt(rqueue, url)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador_diag/diagd.py", line 1463, in load_config_watt
    self._load_ir(rqueue, aconf, fetcher, scc, snapshot)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador_diag/diagd.py", line 1538, in _load_ir
    ir = IR(aconf, secret_handler=secret_handler, cache=self.app.cache)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/ir.py", line 300, in __init__
    MappingFactory.load_all(self, aconf)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/irmappingfactory.py", line 30, in load_all
    cls.load_config(ir, aconf, "Mapping", "mappings", IRHTTPMapping)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/irmappingfactory.py", line 55, in load_config
    mapping = mapping_class(ir, aconf, **config)
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/irhttpmapping.py", line 283, in __init__
    super().__init__(
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/irbasemapping.py", line 105, in __init__
    super().__init__(
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/irresource.py", line 77, in __init__
    self.set_active(self.setup(ir, aconf))
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/irhttpmapping.py", line 306, in setup
    if not super().setup(ir, aconf):
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/irbasemapping.py", line 125, in setup
    self.group_id = self._group_id()
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/ir/irhttpmapping.py", line 439, in _group_id
    h.update(self.prefix.encode('utf-8'))
  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/resource.py", line 89, in __getattr__
    raise AttributeError(key)
AttributeError: prefix
2021/03/23 13:34:54 error notifying diagd: 500 INTERNAL SERVER ERROR, configuration failed
```
This seems to be connected to a mapping with the prefix set to "". E.g.
```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: my-metabase
  namespace: mappings
  labels:
    app: metabase
spec:
  prefix: ""
  rewrite: ""
  service: 'metabase.metabase:80'
  bypass_auth: true
  timeout_ms: 0
  host: my.metabase.url
  labels:
    ambassador:
      - app:
          - metabase
```
After changing the prefix to / the aes was starting fine.

**To Reproduce**
1. Apply above mentioned mapping to your cluster
2. Restart one of your aes:1.12.1 containers and observe it's logs.

**Expected behavior**
No crashing of the container, due to this error.

**Versions (please complete the following information):**
 - Ambassador: [aes:1.12.1]
 - Kubernetes environment [GKE v1.17.15-gke.800]

**Additional context**
I my case I was updating from aes:1.2.2 to aes:1.12.1. Version 1.2.2 was fine with the above prefix setting.

**Comment by jijotj** [comment]
Facing the same issue with v1.13.1 as well.

**Comment by cindymullins-dw** [comment]
In [2.1.2 we fixed a bug](https://www.getambassador.io/docs/emissary/latest/release-notes/) for an empty rewrite in a Mapping.  If you discover this issue persists on 2.x, please reopen.
