### ISSUE TITLE
Ambassador: malformed filter policy crashes AES

### ISSUE THREAD

**Issue by gruffyn** [emissary-ingress/emissary#3390]
**Describe the bug**
Applying a malformed filter policy will cause AES to panic and crash all running pods simultaneously, taking out the gateway.

**To Reproduce**
1. Apply the following filter policy, which is missing the `spec` key:
  ```yaml
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: example
  rules:
  - filters:
    - name: example.filter
      onAllow: break
    host: example.com
    path: /some/path/status
```
2. Observe all ambassador pod states to watch them crash shortly after reading in the above policy.

**Expected behavior**
Ambassador should not crash when attempting to load a malformed filterPolicy.

**Versions (please complete the following information):**
 - Ambassador: 1.13.1
 - Kubernetes environment: EKS
 - Version 1.18.9

**Additional context**
```sh
E0504 15:40:32.254533      16 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1032 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x299ff00, 0x3dd18e0)
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x89
panic(0x299ff00, 0x3dd18e0)
	runtime/panic.go:969 +0x175
github.com/datawire/apro/cmd/amb-sidecar/filters/controller.parseFilterPolicy(0xc0009b09f0, 0xc0008d710e, 0xa, 0x29891d3, 0x7, 0xc000056216, 0x24, 0xc0000520b5, 0xa, 0x0, ...)
	github.com/datawire/apro/cmd/amb-sidecar/filters/controller/controller.go:92 +0x85
github.com/datawire/apro/cmd/amb-sidecar/filters/controller.(*Controller).Watch.func2(0xc0003848c0)
	github.com/datawire/apro/cmd/amb-sidecar/filters/controller/controller.go:176 +0x218
github.com/datawire/ambassador/pkg/k8s.(*Watcher).WatchQuery.func1()
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:121 +0x6c
github.com/datawire/ambassador/pkg/k8s.(*Watcher).WatchQuery.func2(0x2c91160, 0xc0010e2890)
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:130 +0x24
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.newInformer.func1(0x29ca460, 0xc000bf88c0, 0x1, 0xc000bf88c0)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:407 +0x198
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000ce8aa0, 0xc000cf8db0, 0x0, 0x0, 0x0, 0x0)
	k8s.io/client-go@v0.20.2/tools/cache/delta_fifo.go:507 +0x322
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0009f6bd0)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:183 +0x42
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00007df78)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0013bff78, 0x2f4eee0, 0xc004b48510, 0xc000ea6301, 0xc0000a1200)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00007df78, 0x3b9aca00, 0x0, 0x1, 0xc0000a1200)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc0009f6bd0, 0xc0000a1200)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:154 +0x2e5
github.com/datawire/ambassador/pkg/k8s.(*Watcher).WatchQuery.func5()
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:162 +0x42
created by github.com/datawire/ambassador/pkg/k8s.(*Watcher).Start
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:197 +0x374
E0504 15:40:32.254614      16 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1032 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x299ff00, 0x3dd18e0)
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x89
panic(0x299ff00, 0x3dd18e0)
	runtime/panic.go:969 +0x175
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x299ff00, 0x3dd18e0)
	runtime/panic.go:969 +0x175
github.com/datawire/apro/cmd/amb-sidecar/filters/controller.parseFilterPolicy(0xc0009b09f0, 0xc0008d710e, 0xa, 0x29891d3, 0x7, 0xc000056216, 0x24, 0xc0000520b5, 0xa, 0x0, ...)
	github.com/datawire/apro/cmd/amb-sidecar/filters/controller/controller.go:92 +0x85
github.com/datawire/apro/cmd/amb-sidecar/filters/controller.(*Controller).Watch.func2(0xc0003848c0)
	github.com/datawire/apro/cmd/amb-sidecar/filters/controller/controller.go:176 +0x218
github.com/datawire/ambassador/pkg/k8s.(*Watcher).WatchQuery.func1()
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:121 +0x6c
github.com/datawire/ambassador/pkg/k8s.(*Watcher).WatchQuery.func2(0x2c91160, 0xc0010e2890)
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:130 +0x24
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.newInformer.func1(0x29ca460, 0xc000bf88c0, 0x1, 0xc000bf88c0)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:407 +0x198
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000ce8aa0, 0xc000cf8db0, 0x0, 0x0, 0x0, 0x0)
	k8s.io/client-go@v0.20.2/tools/cache/delta_fifo.go:507 +0x322
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0009f6bd0)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:183 +0x42
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00007df78)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0013bff78, 0x2f4eee0, 0xc004b48510, 0xc000ea6301, 0xc0000a1200)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00007df78, 0x3b9aca00, 0x0, 0x1, 0xc0000a1200)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc0009f6bd0, 0xc0000a1200)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:154 +0x2e5
github.com/datawire/ambassador/pkg/k8s.(*Watcher).WatchQuery.func5()
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:162 +0x42
created by github.com/datawire/ambassador/pkg/k8s.(*Watcher).Start
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:197 +0x374
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x261f305]
goroutine 1032 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x299ff00, 0x3dd18e0)
	runtime/panic.go:969 +0x175
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x299ff00, 0x3dd18e0)
	runtime/panic.go:969 +0x175
github.com/datawire/apro/cmd/amb-sidecar/filters/controller.parseFilterPolicy(0xc0009b09f0, 0xc0008d710e, 0xa, 0x29891d3, 0x7, 0xc000056216, 0x24, 0xc0000520b5, 0xa, 0x0, ...)
	github.com/datawire/apro/cmd/amb-sidecar/filters/controller/controller.go:92 +0x85
github.com/datawire/apro/cmd/amb-sidecar/filters/controller.(*Controller).Watch.func2(0xc0003848c0)
	github.com/datawire/apro/cmd/amb-sidecar/filters/controller/controller.go:176 +0x218
github.com/datawire/ambassador/pkg/k8s.(*Watcher).WatchQuery.func1()
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:121 +0x6c
github.com/datawire/ambassador/pkg/k8s.(*Watcher).WatchQuery.func2(0x2c91160, 0xc0010e2890)
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:130 +0x24
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.newInformer.func1(0x29ca460, 0xc000bf88c0, 0x1, 0xc000bf88c0)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:407 +0x198
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000ce8aa0, 0xc000cf8db0, 0x0, 0x0, 0x0, 0x0)
	k8s.io/client-go@v0.20.2/tools/cache/delta_fifo.go:507 +0x322
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0009f6bd0)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:183 +0x42
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00007df78)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0013bff78, 0x2f4eee0, 0xc004b48510, 0xc000ea6301, 0xc0000a1200)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00007df78, 0x3b9aca00, 0x0, 0x1, 0xc0000a1200)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc0009f6bd0, 0xc0000a1200)
	k8s.io/client-go@v0.20.2/tools/cache/controller.go:154 +0x2e5
github.com/datawire/ambassador/pkg/k8s.(*Watcher).WatchQuery.func5()
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:162 +0x42
created by github.com/datawire/ambassador/pkg/k8s.(*Watcher).Start
	github.com/datawire/ambassador@v1.12.2/pkg/k8s/watcher.go:197 +0x374
```

**Comment by cindymullins-dw** [comment]
I believe this was addressed in v2.1.0, [per Release Notes](https://www.getambassador.io/docs/edge-stack/latest/release-notes/): Change: Ambassador Edge Stack CRDs are fully validated
The Ambassador Edge Stack CRDs (Filter, FilterPolicy, and RateLimit) will now be validated for correct syntax by Kubernetes itself. This means that kubectl apply will reject invalid CRDs before they are actually applied, preventing them from causing errors.
