### ISSUE TITLE
ERROR: "could not update Envoy stats: too many values to unpack (expected 2)"  in logs after upgrading helm3 chart from v6.7.13 to v6.9.3 (v1.14.2)

### ISSUE THREAD

**Issue by talshmuli** [emissary-ingress/emissary#3924]
We are upgrading with Helm3 from chart v6.7.13 (v1.13.10) to chart v6.9.3 (v1.14.2) with the same configuration.
and get the following error in the deployment logs with an infinite loop,
It seems that it is not updating the status at http://ambassador:8877/ambassador/v0/diag/

`Traceback (most recent call last):  
File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/diagnostics/envoy_stats.py", line 486, in update  self.update_envoy_stats(last_attempt) File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/diagnostics/envoy_stats.py", line 328, in update_envoy_stats key, value = line.split(":")
2021-11-01 09:43:28 diagd 1.14.2-dev.39+g9cdbc6bf3 [P20TThread-3] ERROR: could not update Envoy stats: too many values to unpack (expected 2) Traceback (most recent call last):  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/diagnostics/envoy_stats.py", line 486, in update self.update_envoy_stats(last_attempt)   File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/diagnostics/envoy_stats.py", line 328, in update_envoy_stats  key, value = line.split(":")  ValueError: too many values to unpack (expected 2)  2021-11-01 09:43:33 diagd 1.14.2-dev.39+g9cdbc6bf3 [P20TThread-3] ERROR: could not update Envoy stats: too many values to unpack (expected 2)  Traceback (most recent call last): File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/diagnostics/envoy_stats.py", line 486, in update  self.update_envoy_stats(last_attempt)  File "/usr/lib/python3.8/site-packages/ambassador-0.0.0.dev0-py3.8.egg/ambassador/diagnostics/envoy_stats.py", line 328, in update_envoy_stats  key, value = line.split(":")   ValueError: too many values to unpack (expected 2) `

 - Kubernetes environment Google Kubernetes Engine

**Comment by will-beep-lamm** [comment]
+1. Also seeing this on AES 2.1.2.

**Comment by LP0101** [comment]
+1, also seeing this with chart v6.9.3

**Comment by fabriziolussana** [comment]
I ran into the same problem upgrading from 1.13 to 1.14 and found out that it was a side-effect of my TLScontext configuration.
I started an interactive shell into the container then pulled envoy stats manually (curl http://localhost:8001/stats) and looked for lines that had more than one colon character.
Each line is supposed to be "key: value", with only one colon on each line, neither key nor value can include a colon or parsing will fail. 
In my case one of the entries in TLScontext.hosts had a ":" in it, which was reflected in a key name (vhost.amassador...) in the stats.

**Comment by cindymullins-dw** [comment]
Thanks for the comments.  With regards to the Host & TLSContext, there was an update that changed the way it worked.  When envoy reads the config it gets stuck at the colon and fails.  The solution is to find that colon in the TLSContext or Host and remove it.  We'll find suitable place in our docs to make note of this.

**Comment by dgaffuri** [comment]
Thanks for you clarifications. I still have a doubt anyway: how can I remove the colon in TLSContext if I need to specify a port in host name because a client out of my control sends it in Host header? Without the hosts entry the content will not match.
`kind:  TLSContext
      name:  tls-external-integration
      hosts:
      - integration.example.com
      - integration.example.com:443
      ca_secret: ca
      cert_required: true
      secret: tls
`

**Comment by kennethaasan** [comment]
We are facing the same issue with gRPC. We need to specify ":443" in hosts to be able to allow all clients to connect
