### ISSUE TITLE
Single namespace mode with Istio integration doesn't work

### ISSUE THREAD

**Issue by Sh1ftry** [emissary-ingress/emissary#4484]
**Describe the bug**
Emissary Ingress integrated with Istio as described in [the documentation](https://www.getambassador.io/docs/emissary/latest/howtos/istio/) starts to misbehave after startup when single namespace mode is enabled. All calls result in 503:

```
ACCESS [2022-09-05T06:45:40.148Z] "GET /test HTTP/1.1" 503 UF,URX 0 224 117 - "xxx" "Blackbox Exporter/0.21.1" "7371c5c5-5800-42a4-b511-5a73cab5e5c8" "xxx" "xxx"
```

**To Reproduce**
1. Install istio
2. Install emissary with istio integration
3. Create a mapping and call the path regularly
4. Observe that calls start to fail after 24h

**Expected behavior**
The calls do not start to fail.

**Versions (please complete the following information):**
 - emissary: 3.1.0
 - kubernetes: 1.23.8
 - istio: 1.14.3

**Additional context**
It might be related with Istio replacing certificate, since it happens 24h after the startup.

**Comment by l1v3** [comment]
Hey there, i've posted a similar (probably the same) issue a few days ago in slack and followed up with more info there because i wasn't sure if we misconfigured something. but since there is now a ticket here, i'll add what i found in case its related.

**Versions**
Istio: 1.14.3
Kubernetes: 1.24.x
Emissary: >= 2.1.0

**Description**
We've upgrade from 2.0.5 to 3.1.0 and noticed that the certificate rotation doesn't work. After the initial cert expires, emissary only reports upstream errors due expired certificate and 503 UF in logs.

**Error in Logs**
```
time="2022-09-01 19:36:10.6843" level=info msg="IstioCert: certificate istio-certs.emissary updated" func="github.com/emissary-ingress/emissary/v3/cmd/entrypoint.(*istioCertWatchManager).Update" file="/go/cmd/entrypoint/istiocert.go:136" CMD=entrypoint PID=1 THREAD=/watcher/loop

2022-09-01 19:36:10 diagd 3.1.0 [P19TAEW] ERROR: could not reconfigure: object of type 'NoneType' has no len()

2022-09-01 19:36:10 diagd 3.1.0 [P19TAEW] ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ambassador-0.0.0.dev0-py3.9.egg/ambassador_diag/diagd.py", line 1480, in run
    self.load_config_watt(rqueue, url)
  File "/usr/lib/python3.9/site-packages/ambassador-0.0.0.dev0-py3.9.egg/ambassador_diag/diagd.py", line 1639, in load_config_watt
    self._load_ir(rqueue, aconf, fetcher, scc, snapshot)
  File "/usr/lib/python3.9/site-packages/ambassador-0.0.0.dev0-py3.9.egg/ambassador_diag/diagd.py", line 1667, in _load_ir
    config_type, reset_cache, invalidate_groups_for = IR.check_deltas(
  File "/usr/lib/python3.9/site-packages/ambassador-0.0.0.dev0-py3.9.egg/ambassador/ir/ir.py", line 141, in check_deltas
    reset_cache = len(fetcher.deltas) > 0
TypeError: object of type 'NoneType' has no len()

time="2022-09-01 19:36:10.7582" level=info msg="error notifying diagd: 500 INTERNAL SERVER ERROR, configuration failed" func=github.com/emissary-ingress/emissary/v3/cmd/entrypoint.notifyWebhookUrl file="/go/cmd/entrypoint/notify.go:141" CMD=entrypoint PID=1 THREAD=/watcher/notifyCh
```

The "Deltas" property within the snapshot-tmp.yaml is null. In 2.1.0 was some code refactored that added an additional line causing the error. 
```
reset_cache = len(fetcher.deltas) > 0 // <-- should this be inside the if statement?
# Next up: are there any deltas?
if fetcher.deltas:
```

my next thought was to disable fast reconfigure since the block is only executed if there is a cache. emissary starts up without the cache, but that function returns reset_cache=True even if there is no cache. which in turn creates a new cache object and the next time its back to that error :confused:

**Comment by cindymullins-dw** [comment]
We seem to have a known issue with service meshes.  The fix is in the works and should be released in the next version.  Could you check [this issue](https://github.com/emissary-ingress/emissary/issues/3510) as well, we believe these are related.

**Comment by l1v3** [comment]
Thanks for the update :) 

Regarding the other issues, i'm not sure if they have the same origin. They all refer to older versions of istio / ambassador, while we were already running newer versions that worked without any issues, even on certificate rotation of istio. The issue for us is only present since emissary version >=2.1.0. We've reverted our emissary upgrade and are now running latest istio with emissary 2.0.5 without any issues.

I do lack the understanding of those delta updates to make any assumption if the state during the rotation is correct or not. The only thing i noticed was the code line above, which felt off to me that the length of deltas is used before checking if they exist in the first place (which causes the error).

**Comment by l1v3** [comment]
@cindymullins-dw i noticed that a new version (3.2.0) was released. Just to keep this updated, the issue is still present.
